sudo: required
services:
  - docker
before_install:
  - docker build -t calebadegbite/complex_client -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script:
  - docker run -e CI=true calebadegbite/complex-client npm test

after_success:
  - docker build -t calebadegbite/complex-client ./client
  - docker build -t calebadegbite/complex-nginx ./nginx
  - docker build -t calebadegbite/complex-server ./server
  - docker build -t calebadegbite/complex-worker ./worker
