sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_ID"
  - echo "$DOCKER_PASSWORD"
  - docker build -t client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client-test npm test

after_success:
  - docker build -t calebadegbite/complex-client ./client
  - docker build -t calebadegbite/complex-nginx ./nginx
  - docker build -t calebadegbite/complex-server ./server
  - docker build -t calebadegbite/complex-worker ./worker

  #LOGIN TO DOCKER
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #PUSH TO DOCKER HUB
  - docker push -t calebadegbite/complex-client
  - docker push -t calebadegbite/complex-nginx
  - docker push -t calebadegbite/complex-server
  - docker push -t calebadegbite/complex-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "complex-docker"
  env: "Complexdocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-767283506971"
  bucket_path: "complex-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
